### ISSUE TITLE
Add search using algolia

### ISSUE THREAD

**Issue by jeddy3** [stylelint/stylelint.io#1]
This would be very useful when a user is searching for a particular rule.

[Algolia](https://www.algolia.com/) would be ideal for our generated static site.

**Comment by MoOx** [comment]
Ref https://github.com/MoOx/statinamic/issues/142 :)

**Comment by jeddy3** [comment]
Excellent! :) I'll keep a close eye on both the statinamic and putaindecode repos.

**Comment by thangngoc89** [comment]
I'm implementing this in my blog. 

Ref: Webpack plugin https://github.com/thangngoc89/blog/blob/aa40e1b710c06112006ac175972338467adb56b3/web_modules/utils/statinamic-agolia-plugin.js

Use it: https://github.com/thangngoc89/blog/blob/aa40e1b710c06112006ac175972338467adb56b3/scripts/webpack.config.babel.js#L141-L160

The only thing left is write a component.

**Comment by jeddy3** [comment]
That looks great!

**Comment by threehams** [comment]
How many unique visitors do you get on stylelint.io? I'm fine with working on this, as long as we won't hit the 100,000 operation limit per month.

**Comment by jeddy3** [comment]
> How many unique visitors do you get on stylelint.io?

About 300 a day. I think that puts us well under the 100,000 operation limit per month.

>  I'm fine with working on this, as long as we won't hit the 100,000 operation limit per month.

Excellent! Good luck :)

**Comment by jeddy3** [comment]
@threehams FYI, I emailed the Algolia guys. The were happy to give us on an open source plan, but they recommend we use their [DocSearch](https://community.algolia.com/docsearch/) service instead as it better fits our needs.

They've kindly set us up an account. We now need to implement it, following their instructions:

----

- Copy the following CSS/JS snippets and add them to your page

```html
<!-- at the end of the HEAD -->
<link rel="stylesheet" href="https://cdn.jsdelivr.net/docsearch.js/2/docsearch.min.css" />
<!-- at the end of the BODY -->
<script type="text/javascript" src="https://cdn.jsdelivr.net/docsearch.js/2/docsearch.min.js"></script>
<script type="text/javascript"> docsearch({
  apiKey: '29d680ce97507c5cd2836c6c74783c05',
  indexName: 'stylelint',
  inputSelector: '### REPLACE ME ####',
  debug: false // Set debug to true if you want to inspect the dropdown
});
</script>
```

- Add a search input if you don't have any yet, and update the inputSelector value in the code snippet to a CSS selector that targets your input field.
- Optionally customize the look and feel by following the DocSearch documentation (https://community.algolia.com/docsearch/documentation/)
- You can also check your configuration in the github repo (https://github.com/algolia/docsearch-configs/blob/master/configs/stylelint.json). Feel free to open pull requests!

---

Let me know if you think you'll have time to jump on this, otherwise I'll try to look into it in the next few days?

**Comment by threehams** [comment]
This is a busy month, but that looks simple enough. I'll look at how the static site is generated in this repo, probably tonight.

**Comment by threehams** [comment]
Well, somewhere between Helmet and Phenomic, I'm lost.

Here's where I'm leaving off tonight:
https://github.com/threehams/stylelint.io/commit/7600deb3a537d8b39d7dc3e4b110377919998f8d

I've learned that:
- When rendered server-side, Helmet adds scripts to the body tag - perfect! Everything works. On the client, it adds scripts to the head. This is by design, but it means the dev server throws errors since `window.docsearch` isn't available. In addition, both tags are duplicated in `<head>` on any client-side route change.
- I can't figure out how to add to `<body>` using Phenomic. A script tag added to LayoutContainer/index.js will not load, and an inline script tag with innerHTML set will not execute.
- Both these solutions kind of make me sad, anyway. It'd be nice if docsearch could load async, though I understand it's designed for static sites.

**Comment by MoOx** [comment]
@threehams you might be interested by this https://github.com/MoOx/phenomic/pull/769

I will try to help you on this as I am currently making some change to phenomic static rendering.

The problem is that the snippet you mentionned can be tricky to use since (depending on your layout and "stuff"), you referenced "inputSelector" might be mounted/unmounted (so algolia js will lost it).

I will ensure the implementation referenced before will work and if necessary, I will make some changes.

**Comment by jeddy3** [comment]
@threehams Thanks for making a start on it!

@MoOx Thanks for the heads up and for looking into this for us. I hadn't noticed https://github.com/MoOx/phenomic/pull/769 (as I was mentioned as @-jeddy3 within it). It looks great. 

@threehams I'll port the implementation over to this repo as I've been working on a branch that updates phenomic to the latest version, and I think finishing the work on that branch _before_ adding this implementation might now be prudent. I'll hopefully have time to do this tomorrow.

**Comment by jeddy3** [comment]
FYI, going to wait on the [release of](https://github.com/MoOx/phenomic/pull/876) `phenomic@0.19` before finishing the phenomic update, and thus enabling search.

**Comment by MoOx** [comment]
phenomic@0.19 is out and the website have a search bar, you can probably handle it now :)

**Comment by jeddy3** [comment]
Sweet. Thanks for the heads-up @MoOx. I hope to make time tomorrow evening to update to `@0.19`, make use of the lovely new base theme and borrow the search bar from the phenomic docs site! :)

Congrats on the release of `@0.19` btw. It's looking very nice!
