### ISSUE TITLE
Search for e.g. custom-property-pattern lead to 404 even though doc for it exists.

### ISSUE THREAD

**Issue by DerZyklop** [stylelint/stylelint.io#286]
### Describe the documentation issue

When I go to https://stylelint.io/ and search for `custom-property-pattern` I get a result in the search-results-card. When i click it/hit enter it brings me to a 404 on
`user-guide/rules/list/#custom-property-1`
when i reload i get redirected to 
`user-guide/rules/#custom-property-1`
The last mentioned page has already an entry for the patterns of this PR, but the correct anchor link would be #pattern 
Anyway… there is also a own page for `custom-property-pattern`:
user-guide/rules/custom-property-pattern/

Related: https://github.com/stylelint/stylelint/pull/6391

### What solution would you like to see?

A search for `custom-property-pattern` brings me to https://stylelint.io/user-guide/rules/custom-property-pattern/

**Comment by ybiquitous** [comment]
Maybe, I guess this issue is related to Algolia search. We may need to update the search index or something else.

**Comment by jeddy3** [comment]
@DerZyklop Thanks for the report. I've fixed the issue.

You were right, @ybiquitous. It was related to Algolia search. I've not delved into the Algolia control panel before, but figured this was probably the right time to learn how it all works. You'll find the access details for Algolia in the shared password vault if you're curious to take a look yourself. I triggered a new crawl. (You'll find that option under "Data sources" (in the bottom right) and then "Crawler".)

> A search for custom-property-pattern brings me to https://stylelint.io/user-guide/rules/custom-property-pattern/

The new crawl picked up the new URLs, i.e. `/rules/<name>` rather than `/rules/list/<name>`. However, the search results for "custom-property-pattern" did not include the actual page for the rule, only the mention of it on the list page. I believe this was a long-standing issue we've had since updating to Docusaurus 2. It seemed `<h1>`s weren't being indexed. I dug deeper and tweaked the configuration for the crawler itself (you'll find this under the "Editor" menu option within the "Crawler" app) so that `<h1>` are indexed.

The search results seem clearer now, with hierarchies shown. For example:

<img width="561" alt="Screenshot 2022-10-19 at 23 04 57" src="https://user-images.githubusercontent.com/808227/196815336-b1cb9359-6cdc-4f95-8450-877c8848b3a8.png">

And with the actual rule pages appearing in the results:

<img width="560" alt="Screenshot 2022-10-19 at 23 05 43" src="https://user-images.githubusercontent.com/808227/196815351-8167d345-7b4d-4e36-a442-25da98f1da99.png">

**Comment by ybiquitous** [comment]
@jeddy3 Thank you so much for fixing the issue and sharing knowledge about the Aloglia search! 🙌🏼 

I could touch the Algolia control panel and crawler editor, and then understand what you explained.

We now have a much better experience with searching on the website! 😄
