### ISSUE TITLE
Include Awesome Stylelint on stylelint.io

### ISSUE THREAD

**Issue by ybiquitous** [stylelint/stylelint.io#370]
### What is the problem you're trying to solve?

We have some links to [Awesome Stylelint](https://github.com/stylelint/awesome-stylelint), but they're external so visitors have to jump to github.com apart from stylelint.io. This experience may not be so useful.

### What solution would you like to see?

So, can we include Awesome Stylelint's README document on this website? It should be possible by changing the [build script](https://github.com/stylelint/stylelint.io/blob/c734cda5c0e8459fbe7cf46dcf50b975b1f5a0ef/scripts/generate-docs.mjs).

E.g. https://stylelint.io/user-guide/awesome-stylelint

**Comment by jeddy3** [comment]
> So, can we include Awesome Stylelint's README document on this website? It should be possible by changing the [build script](https://github.com/stylelint/stylelint.io/blob/c734cda5c0e8459fbe7cf46dcf50b975b1f5a0ef/scripts/generate-docs.mjs).

SGTM. 

> E.g. https://stylelint.io/user-guide/awesome-stylelint

Let's:

- go with https://stylelint.io/awesome-stylelint
- add it to the [right side of the main navigation](https://github.com/stylelint/stylelint.io/blob/c734cda5c0e8459fbe7cf46dcf50b975b1f5a0ef/docusaurus.config.js#L40) 

So that we keep the sidebar for stuff in the `stylelint/stylelint` repo.

**Comment by ybiquitous** [comment]
🎉 Published! https://stylelint.io/awesome-stylelint
