### ISSUE TITLE
git hook under complimentary tools

### ISSUE THREAD

**Issue by awebdeveloper** [stylelint/stylelint.io#41]
Can you include my pre-commit hook somewhere

https://github.com/awebdeveloper/pre-commit-stylelint

**Comment by jeddy3** [comment]
@awebdeveloper Thanks for the suggestion.

Feel free to create a PR to add your tool to the [complementary tools](https://github.com/stylelint/stylelint/blob/master/docs/user-guide/complementary-tools.md) list within the main docs. I suggest adding a new "Version control" heading at the bottom of the list and adding your tool there.

Thanks.

FYI, this repo only contains the code for building the website from the stylelint docs. So, I'll close the issue here.
