### ISSUE TITLE
Redirect `master--stylelint` to new site

### ISSUE THREAD

**Issue by nickofthyme** [stylelint/stylelint.io#471]
Could you please take down https://master--stylelint.netlify.app/?

From the looks of it, this is an old docs page for `v14`. The issue is that google is indexing this page for deprecated/removed rules, instead of surfacing the latest [migration guide](https://stylelint.io/migration-guide/to-15/) on top.

There's no clear indication that these docs are from an old version, other than the [migration guide](https://master--stylelint.netlify.app/migration-guide/to-14), which could confuse people.

<img width="821" alt="Image" src="https://github.com/user-attachments/assets/a756243d-703f-4979-a04d-f24a29732f14" />

Thanks!

**Comment by jeddy3** [comment]
@nickofthyme Thanks for the report. 

Netilfy usually deletes old deployments after 90 days. However, as @Mouvedia pointed out, `master` seems to be sticking around, as it is the most recent successful deployment from that branch.

With some jiggery-pokery, I've deployed a `master` branch of the site with redirects to https://stylelint.io.

I've [also setup redirects](https://github.com/stylelint/stylelint.io/pull/472) on `main` so that Google doesn't start indexing https://stylelint.netilfy.app/.

---

> @jeddy3 I tried to transfer this issue to stylelint/stylelint.io but it failed.

This will be resolved by https://github.com/stylelint/stylelint/issues/8196 when we adopt org-wide permissions.

**Comment by nickofthyme** [comment]
Beautiful! Thanks for the immediate action.
